// Kanonska imena brendova — key je lowercase, value je display ime
// null = ignoriši (nije pravi brend)
const BRAND_MAP: Record<string, string | null> = {
  // === Top brendovi (90%+ proizvoda) ===
  "bosch": "Bosch",
  "makita": "Makita",
  "einhell": "Einhell",
  "metabo": "Metabo",
  "dewalt": "DeWalt",
  "villager": "Villager",
  "ingco": "Ingco",
  "milwaukee": "Milwaukee",
  "hikoki": "HiKOKI",
  "stanley": "Stanley",
  "proxxon": "Proxxon",
  "scheppach": "Scheppach",
  "flex": "Flex",
  "dremel": "Dremel",
  "festool": "Festool",
  "yato": "Yato",
  "bosch diy": "Bosch DIY",
  "graphite": "Graphite",
  "wolfcraft": "Wolfcraft",
  "verto": "Verto",
  "ryobi": "Ryobi",
  "dck": "DCK",
  "eibenstock": "Eibenstock",
  "fieldmann": "Fieldmann",
  "deli": "Deli",
  "carat": "Carat",
  "bormann": "Bormann",
  "ferm": "Ferm",
  "bernardo - maschinen": "Bernardo",
  "cat": "CAT",
  "telwin": "Telwin",
  "rothenberger": "Rothenberger",
  "scangrip": "Scangrip",
  "agm": "AGM",
  "workers best": "Workers Best",
  "bihui": "Bihui",
  "daewoo": "Daewoo",
  "ridgid": "Ridgid",
  "garden": "Garden",
  "fein": "Fein",
  "femi": "Femi",
  "blade": "Blade",
  "collomix": "Collomix",
  "hazet": "Hazet",
  "echo": "Echo",
  "rems": "REMS",
  "gardenmaster": "Gardenmaster",
  "tyrolit": "Tyrolit",
  "gesipa": "Gesipa",
  "wadfow": "Wadfow",
  "machtig": "Machtig",
  "gude": "Güde",
  "güde": "Güde",
  "ruris": "Ruris",
  "evolution": "Evolution",
  "ks": "KS",
  "richmann": "Richmann",
  "kwb": "KWB",
  "beta": "Beta",
  "ronix": "Ronix",
  "neo": "NEO",
  "hitachi": "HiKOKI", // rebrand
  "womax": "Womax",
  "womax premium": "Womax",
  "womax green power": "Womax",
  "senco": "Senco",
  "gardena": "Gardena",
  "wiha": "Wiha",
  "irimo": "Irimo",
  "vigor": "Vigor",
  "varta": "Varta",
  "deca": "Deca",
  "stiga": "Stiga",
  "stihl": "Stihl",
  "commel": "Commel",
  "tolsen": "Tolsen",
  "topex": "Topex",
  "unior": "Unior",
  "knipex": "Knipex",
  "extol": "Extol",
  "emos": "Emos",
  "trumpf": "Trumpf",
  "rubi": "Rubi",
  "raider": "Raider",
  "micron": "Micron",
  "levior": "Levior",
  "beorol": "Beorol",
  "gedore": "Gedore",
  "bosch expert": "Bosch",
  "esab": "ESAB",
  "holzmann maschinen": "Holzmann",
  "holzmann": "Holzmann",
  "mirka": "Mirka",
  "b&w": "B&W",
  "gys": "GYS",
  "högert technik": "Högert",
  "hogert": "Högert",
  "swisstech": "SwissTech",
  "winbag": "Winbag",
  "honda": "Honda",
  "klauke": "Klauke",
  "chicago": "Chicago Pneumatic",
  "chicago pneumatic": "Chicago Pneumatic",
  "lemania": "Lemania",
  "rem": "REM",
  "strong": "Strong",
  "karcher": "Kärcher",
  "kärcher": "Kärcher",
  "impakt": "Impakt",
  "max": "MAX",
  "wagner": "Wagner",
  "zipper": "Zipper",
  "xtar": "XTAR",
  "jei": "JEI",
  "hausmax": "Hausmax",
  "husqvarna": "Husqvarna",
  "novus": "Novus",
  "rapid": "Rapid",
  "wurth": "Würth",
  "limex": "Limex",
  "stocker": "Stocker",
  "bahco": "Bahco",
  "fervi": "Fervi",
  "zenesis": "Zenesis",
  "bohrcraft": "Bohrcraft",
  "klingspor": "Klingspor",
  "pilana": "Pilana",
  "bluebird": "Bluebird",
  "skil": "Skil",
  "profiair": "ProfiAir",
  "tjep": "TJEP",
  "oleo-mac": "Oleo-Mac",
  "avatar": "Avatar",
  "matrix": "Matrix",
  "heinner": "Heinner",
  "optrel": "Optrel",
  "bavaria": "Bavaria",
  "ingersoll": "Ingersoll Rand",
  "kaufmann": "Kaufmann",
  "weidmuller": "Weidmüller",
  "ega master": "EGA Master",
  "steinel": "Steinel",
  "sandberg": "Sandberg",
  "xiaomi": "Xiaomi",
  "usag": "USAG",
  "portwest": "Portwest",
  "greenlee": "Greenlee",
  "virutex": "Virutex",
  "pferd": "Pferd",
  "metallkraft": "Metallkraft",
  "bds": "BDS",
  "optimum": "Optimum",
  "hammer": "Hammer",
  "iskra": "Iskra",
  "total alati": "Total",

  // === Black+Decker aliasi ===
  "black+decker": "Black+Decker",
  "black&decker": "Black+Decker",
  "blackdecker": "Black+Decker",

  // === Typo/rebrand ===
  "boch": "Bosch",
  "matabo": "Metabo",
  "makira": "Makita",
  "мakita": "Makita", // ćirilično M
  "borman": "Bormann",
  "maktec": "Makita",

  // === Ignoriši — nisu brendovi ===
  "ostalo": null,
  "ostali proizvodjaci": null,
  "super": null,
  "aku": null,
  "aku.": null,
  "akumulatorski": null,
  "akumulatorska": null,
  "akumulatorsko": null,
  "elektro": null,
  "električni": null,
  "električna": null,
  "brusilica": null,
  "testera": null,
  "trimer": null,
  "mikser": null,
  "usisivač": null,
  "mašina": null,
  "stacionarna": null,
  "recipro": null,
  "kružna": null,
  "čeona": null,
  "šlajferica": null,
  "udarna": null,
  "ručna": null,
  "rezna": null,
  "lenjir": null,
  "šipka": null,
  "mini": null,
  "set": null,
  "promo": null,
  "home": null,
  "fix": null,
  "black": null,
  "akcijski": null,
  "univerzalni": null,
  "3": null,
  "2": null,
  "5": null,
  "3 e": null,
};

// Model brojevi koji su pogrešno parsirani kao brendovi
const MODEL_NUMBER_PATTERN = /^[A-Z]{0,3}\d{2,}/i;

export function normalizeBrand(raw: string | null | undefined): string | null {
  if (!raw) return null;

  const trimmed = raw.trim();
  if (!trimmed) return null;

  const key = trimmed.toLowerCase();

  // Eksplicitan lookup
  if (key in BRAND_MAP) {
    return BRAND_MAP[key];
  }

  // Filtriraj model brojeve (DHP485Z, GA9050, HR005GZ01, itd.)
  if (MODEL_NUMBER_PATTERN.test(trimmed)) {
    return null;
  }

  // Fallback: title case
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1).toLowerCase();
}

export { BRAND_MAP };
